opt_in_rules:
  - private_outlet
  - strong_iboutlet
  - private_action

disabled_rules:
  - type_body_length
  - file_length
  - trailing_comma
  - type_name
  - function_parameter_count

  - function_body_length

  - cyclomatic_complexity
  - todo
  - nesting
  - force_try
  - unused_setter_value
  - weak_delegate

included:
  - UniGears
  - UnitTests
  - vertical_whitespace

excluded:
  - Pods

line_length: 160

force_cast:
 severity: warning